name: Unexpected Error Report2
description: Please help the development of Revnobot by reporting "Something Went Wrong!" messages
title: "User Reported Bug"
labels: ["bug tagged with error id"]
assignees:
  - Revnoplex
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: error-id
    attributes:
      label: Error ID
      description: Please Specify the error id that was outputted from the "Something Went Wrong!" message
      placeholder: VINT-CT-PID-MID-TS
    validations:
      required: true
  - type: textarea
    id: error-env
    attributes:
      label: Describe the environment
      description: Describe what you or the bot was doing when the error occured.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots showing the channel the error occurred in
      placeholder: Screenshot URLs. Separete by line
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
